server:
    port: 8082

spring:
    application:
        name: match-engine
    datasource:
        url: jdbc:postgresql://localhost:5432/match_engine_db
        username: postgres
        password: PG@admin2800
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 2
            idle-timeout: 30000
            pool-name: match-engine-hikari
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: match-engine-consumer-group
            auto-offset-reset: latest # Only new messages, avoids old/corrupt data
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: com.gracemann.recon.matchengine.dto
                spring.json.value.default.type: com.gracemann.recon.matchengine.dto.MatchEngineTxnDTO
            enable-auto-commit: false
            max-poll-records: 1000
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: all
        listener:
            missing-topics-fatal: false

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, prometheus
    endpoint:
        health:
            show-details: always

logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.springframework.kafka: WARN
        com.gracemann.recon.matchengine: DEBUG

matchengine:
    batch:
        default-size: 10000
        max-retries: 3
        match-confidence-threshold: 0.95
